name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
    
    - uses: actions/setup-dotnet@v1
    - name: use latest dotnet core
      with:
        dotnet-version: 5.x
        
    - name: Restore dependencies
      run: dotnet restore BDInfo.Core/BDInfo.Core.sln
    - name: Build
      run: dotnet build BDInfo.Core/BDInfo.Core.sln --no-restore
    - name: Test
      run: dotnet test BDInfo.Core/BDInfo.Core.sln --no-build --verbosity normal
    - name: Create linux x64 portable
      run: dotnet publish BDInfo.Core/BDInfo.Core.sln -r linux-x64 -c release --self-contained
