name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x
    - name: Add organization git
      run: dotnet nuget add source --username Sonic3R --password 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 --store-password-in-clear-text --name github "https://nuget.pkg.github.com/dotnetcorecorner/index.json"
    - name: Restore dependencies
      run: dotnet restore BDInfo.Core/BDInfo.Core.sln
    - name: Build against errors
      run: dotnet build BDInfo.Core/BDInfo.Core.sln --no-restore     
    - name: Create self-contained binary for BDInfo
      run: dotnet publish BDInfo.Core/BDInfo/BDInfo.csproj -c Release -r linux-x64 --self-contained
    - name: Create self-contained binary for BDExtractor
      run: dotnet publish BDInfo.Core/BDExtractor/BDExtractor.csproj -c Release -r linux-x64 --self-contained
      
    - name: BDInfo Zip Release
      # You may pin to the exact commit or the version.
      # uses: TheDoctor0/zip-release@591e9b128012d3328db6043d0d0266c3ac27f9b5
      uses: TheDoctor0/zip-release@0.6.1
      with:
        # Filename for archive
        filename: bdinfo.zip
        # Base path for archive files
        path: BDInfo.Core/BDInfo/bin/Release/netcoreapp3.1/linux-x64/publish
        # Working directory before zipping
        directory: .
        # List of excluded files / directories
        #exclusions: # optional, default is 
        # Tool to use for archiving
        type: zip
        
    - name: BDExtractor release
      uses: TheDoctor0/zip-release@0.6.1
      with:
        # Filename for archive
        filename: bdextractor.zip
        # Base path for archive files
        path: BDInfo.Core/BDExtractor/bin/Release/netcoreapp3.1/linux-x64/publish/
        # Working directory before zipping
        directory: .
        # List of excluded files / directories
        #exclusions: # optional, default is 
        # Tool to use for archiving
        type: zip
        
    - name: Release & Assets
      # You may pin to the exact commit or the version.
      # uses: Hs1r1us/Release-AIO@354b8db50d5b6310b621cb6c5e29d1f8e611aff7
      uses: Hs1r1us/Release-AIO@v1.0
      with:
        # The name of the tag
        tag_name: v1.0.0
        # The name of the release
        release_name: BDInfo
        # Text describing the contents of the tag
        #body: # optional
        # Path to file with information about the tag
        #body_path: # optional
        # The path to the asset you want to upload
        asset_files: bdinfo.zip
        # `true` to create a draft (unpublished) release, `false` to create a published one. Default: `false`
        draft: false # optional
        # `true` to identify the release as a prerelease. `false` to identify the release as a full release. Default: `false`
        prerelease: false# optional
        # Repository on which to release.  Used only if you want to create the release on another repo
        #repo: # optional
