name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x
    - name: Restore dependencies
      run: dotnet restore BDInfo.Core/BDInfo.Core.sln
    - name: Build
      run: dotnet build BDInfo.Core/BDInfo.Core.sln --no-restore
    - name: Test
      run: dotnet test BDInfo.Core.sln --no-build --verbosity normal
    - name: Create self-contained binaries
      run: dotnet publish BDInfo.Core/BDInfo.Core.sln -c Release -r linux-x64 --self-contained
